### ISSUE TITLE
Update readme comparing to Catberry 8

### ISSUE THREAD

**Issue by pragmader** [catbee/catbee#43]
> Browserify Plugins
> Catberry support browserify transforms, we also support pluggins.

Catberry supports browserify plugins since [7.1.0](https://github.com/catberry/catberry/releases/tag/7.1.0)

> New logger system
> Catbee use winston as server logger instead Log4js used in Catberry. Also, we add special YAML-like console formatter.

It's worth to mention that since [8.0.0](https://github.com/catberry/catberry/releases/tag/8.0.0) Catberry does not include logger at all. Now the logger is a regular plugin for Catberry and you can choose any creating an adapter like for a template engine, we offer a [stupid console logger](https://github.com/catberry/catberry-logger) by default.

> this.$context.state
> State instance available in this.$context as read-only object.

That's confusing, what's the difference? The `state` is a frozen object in Catberry that means it's read-only as well.

> All other API fully compatible with Catberry

As far as I know that's not true anymore. Catberry dependency injection support, UHR and logger became separate plugins and [more](https://github.com/catberry/catberry/wiki/Migration-from-7.x-to-8.x)

**Comment by markuplab** [comment]
Now we rework documentation for Catbee@3.0.0 release.
I think we remove comparing list from repo.

> That's confusing, what's the difference? The state is a frozen object in Catberry that means it's read- only as well.

`this.$context.state` is State class instance, not url state.

**Comment by pragmadash** [comment]
>this.$context.state is State class instance, not url state.

Got it, in this case I would add more details about the difference.

**Comment by rdner** [comment]
Closing, can't find this comparison anymore.
