### ISSUE TITLE
Alpha 3.0.0 Bugs

### ISSUE THREAD

**Issue by markuplab** [catbee/catbee#54]
Report all bugs here.

- [x] Router match all routes, because args every time object, instead of null
- [x] Infinity loading if head component defined in document template, but not defined in document children
- [x] Props should be empty object if not provided by parent component
- [x] If watcher is not defined, `this.$context.getWatcherData` should resolve promise instead of return null

**Comment by artem-malko** [comment]
@markuplab There is a link to request?)
